version: 0.2
env:
  variables:
    INSTANCE_TYPE: "t2.micro"
    KEY_NAME: "yasirKP-ohio"
    AMI_ID: "ami-0fc20dd1da406780b"
    TAG_NAME: "cfn-cp3"

phases:
  # install:
  #   commands:
  #     - key=$(echo "sikandar-keypair-ohio")
  build:
    commands:
      - echo "Hello World"
      # - key=$(echo "sikandar-keypair-ohio")
      # - echo $key
      - echo '{"Parameters":{"InstanceType":"'$INSTANCE_TYPE'"}}' | jq . >output.json
      - cat output.json 
  # build:
  #   commands:
  #     - aws cloudformation deploy --template-file template.yaml --stack-name sample-stack --parameter-overrides InstanceType=$INSTANCE_TYPE KeyName=$KEY_NAME AmiId=$AMI_ID TagName=$TAG_NAME
  
artifacts:
  files:
    - output.json