version: 0.2
env:
  variables:
    TagName: "cfn-cp3"
    KeyName: "yasirKP-ohio"
    InstanceType: "t2.micro"
    AmiId: "ami-0fc20dd1da406780b"

phases:
  build:
    commands:
      - jq -n '{Parameters:{TagName:"'$TagName'",KeyName:"'$KeyName'",InstanceType:"'$InstanceType'",AmiId:"'$AmiId'"}}' >output.json
      - cat output.json   
artifacts:
  files:
    - output.json