version: 0.2

phases:
  build:
    commands:
      - jq -n '{Parameters:{TagName:"'$TagName'",KeyName:"'$KeyName'",InstanceType:"'$InstanceType'",AmiId:"'$AmiId'"}}' >output.json
      - cat output.json   
artifacts:
  files:
    - output.json