version: 0.2
env:
  variables:
    # INSTANCE_TYPE: "t2.micro"
    # KEY_NAME: "yasirKP-ohio"
    # AMI_ID: "ami-0fc20dd1da406780b"
    TagName: "cfn-cp3"

phases:
  # pre_build:
  #   commands:
  #     - echo "Installing jq..."
  #     - apt update -y
  #     - apt install jq -y
  build:
    commands:
      # - echo '{"ParameterKey":"'TagName'"}' | jq --arg ParameterKey ParameterValue '. + {ParameterValue:"'$TagName'"}' >output.json
      # - jq -n '[{ParameterKey:"TagName",ParameterValue:"'$TagName'"}]' >output.json
      - jq -n '{Parameters:{TagName:"'$TagName'"}}' >output.json
      - cat output.json   
artifacts:
  files:
    - output.json