Description: "testing params using codepipeline."
Parameters:
  InstanceType:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be a valid and existing key pair name.
  AmiId:
    Type: String
  TagName:
    Type: String
Resources:
  Ec2:
    Type: AWS::EC2::Instance
    Properties:
       IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AmiId
      NetworkInterfaces:
      - DeviceIndex: '0'
        AssociatePublicIpAddress: 'true'
        DeleteOnTermination: 'true'
      Tags:
      - Key: Name
        Value: !Ref TagName
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
        Version: '2012-10-17'
      Path: /
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: insprofile
      Path: /
      Roles:
        -
          Ref: "Role"
  